language: python
python:
  - "3.6"
  - "3.7"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run py.test tests
  - pipenv run mypy --ignore-missing-imports --strict-optional --check-untyped-defs talepy/
  - pipenv run flake8 talepy tests
  - pipenv run isort --recursive --check-only talepy tests