language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install
script:
  - py.test tests
  - mypy --ignore-missing-imports --strict-optional --check-untyped-defs talepy/
  - flake8 talepy tests
  - isort --recursive --check-only talepy tests